### ISSUE TITLE
pygraphviz error

### ISSUE THREAD

**Issue by Phoenix1112** [mandatoryprogrammer/TrustTrees#19] opened 2019-09-07 22:35 UTC
os : kali linux (Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux)

i installed : graphviz   and  graphviz-dev

sudo pip install TrustTrees

> Collecting TrustTrees
  Using cached https://files.pythonhosted.org/packages/9c/fd/baa50e7ad4e82226c99cc1cf9ed15197bd7c2e1cf22a25b63201213e5c23/TrustTrees-2.0.1-py3-none-any.whl
Collecting tldextract==2.0.2 (from TrustTrees)
  Using cached https://files.pythonhosted.org/packages/70/4e/08c9a650e2a67b1bb27137be0aeb879755984ca6efb58d26e5c1af42ddce/tldextract-2.0.2-py2.py3-none-any.whl
Collecting graphviz==0.6 (from TrustTrees)
  Using cached https://files.pythonhosted.org/packages/ff/81/14ad4d67841aca1522c00eaad9e751dcab8f49958e0a3f474c483904d532/graphviz-0.6-py2.py3-none-any.whl
Requirement already satisfied: requests-file==1.4.1 in /usr/local/lib/python3.7/dist-packages (from TrustTrees) (1.4.1)
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python3.7/dist-packages (from TrustTrees) (1.10.0)
Requirement already satisfied: requests==2.13.0 in /usr/local/lib/python3.7/dist-packages (from TrustTrees) (2.13.0)
Requirement already satisfied: pyOpenSSL==19.0.0 in /usr/lib/python3/dist-packages (from TrustTrees) (19.0.0)
Collecting pygraphviz==1.3.1 (from TrustTrees)
  Using cached https://files.pythonhosted.org/packages/98/bb/a32e33f7665b921c926209305dde66fe41003a4ad934b10efb7c1211a419/pygraphviz-1.3.1.tar.gz
Requirement already satisfied: idna==2.5 in /usr/local/lib/python3.7/dist-packages (from TrustTrees) (2.5)
Requirement already satisfied: dnspython==1.15.0 in /usr/local/lib/python3.7/dist-packages (from TrustTrees) (1.15.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tldextract==2.0.2->TrustTrees) (41.0.1)
Building wheels for collected packages: pygraphviz
  Running setup.py bdist_wheel for pygraphviz ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t2ega3lc/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-nb3oob74 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pygraphviz
  copying pygraphviz/agraph.py -> build/lib.linux-x86_64-3.7/pygraphviz
  copying pygraphviz/graphviz.py -> build/lib.linux-x86_64-3.7/pygraphviz
  copying pygraphviz/release.py -> build/lib.linux-x86_64-3.7/pygraphviz
  copying pygraphviz/version.py -> build/lib.linux-x86_64-3.7/pygraphviz
  copying pygraphviz/__init__.py -> build/lib.linux-x86_64-3.7/pygraphviz
  creating build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_edge_attributes.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_drawing.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_graph.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_subgraph.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_string.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_attribute_defaults.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_html.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_unicode.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_readwrite.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_attributes.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_layout.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_node_attributes.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/test_clear.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  copying pygraphviz/tests/__init__.py -> build/lib.linux-x86_64-3.7/pygraphviz/tests
  running egg_info
  writing pygraphviz.egg-info/PKG-INFO
  writing dependency_links to pygraphviz.egg-info/dependency_links.txt
  writing top-level names to pygraphviz.egg-info/top_level.txt
  reading manifest file 'pygraphviz.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '.svn' found anywhere in distribution
  no previously-included directories found matching 'doc/build'
  writing manifest file 'pygraphviz.egg-info/SOURCES.txt'
  copying pygraphviz/graphviz.i -> build/lib.linux-x86_64-3.7/pygraphviz
  copying pygraphviz/graphviz_wrap.c -> build/lib.linux-x86_64-3.7/pygraphviz
  running build_ext
  building 'pygraphviz._graphviz' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/pygraphviz
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c pygraphviz/graphviz_wrap.c -o build/temp.linux-x86_64-3.7/pygraphviz/graphviz_wrap.o
  pygraphviz/graphviz_wrap.c: In function ‘agattr_label’:
  pygraphviz/graphviz_wrap.c:3321:12: warning: returning ‘Agsym_t *’ {aka ‘struct Agsym_s *’} from a function with return type ‘int’ makes integer from pointer without a cast [-Wint-conversion]
       return agattr(g, kind, name, val);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.7/pygraphviz/graphviz_wrap.o -lcgraph -lcdt -o build/lib.linux-x86_64-3.7/pygraphviz/_graphviz.cpython-37m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  Trying pkg-config
  Failed to find pkg-config
  Trying dotneato-config
  Failed to find dotneato-config
  Failed to find dotneato-config
  
  Your Graphviz installation could not be found.
  
          1) You don't have Graphviz installed:
             Install Graphviz (http://graphviz.org)
  
          2) Your Graphviz package might incomplete.
             Install the binary development subpackage (e.g. libgraphviz-dev or similar.)
  
          3) You are using Windows
             There are no PyGraphviz binary packages for Windows but you might be
             able to build it from this source.  See
             http://networkx.lanl.gov/pygraphviz/reference/faq.html
  
          If you think your installation is correct you will need to manually
          change the include_dirs and library_dirs variables in setup.py to
          point to the correct locations of your graphviz installation.
  
          The current setting of library_dirs and include_dirs is:
  library_dirs=None
  include_dirs=None
  
  error: Error locating graphviz.
  
  ----------------------------------------
  Failed building wheel for pygraphviz
  Running setup.py clean for pygraphviz
Failed to build pygraphviz
Installing collected packages: tldextract, graphviz, pygraphviz, TrustTrees
  Running setup.py install for pygraphviz ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t2ega3lc/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-annpjoys/install-record.txt --single-version-externally-managed --compile:
    running install
    Trying pkg-config
    Failed to find pkg-config
    Trying dotneato-config
    Failed to find dotneato-config
    Failed to find dotneato-config
    
    Your Graphviz installation could not be found.
    
            1) You don't have Graphviz installed:
               Install Graphviz (http://graphviz.org)
    
            2) Your Graphviz package might incomplete.
               Install the binary development subpackage (e.g. libgraphviz-dev or similar.)
    
            3) You are using Windows
               There are no PyGraphviz binary packages for Windows but you might be
               able to build it from this source.  See
               http://networkx.lanl.gov/pygraphviz/reference/faq.html
    
            If you think your installation is correct you will need to manually
            change the include_dirs and library_dirs variables in setup.py to
            point to the correct locations of your graphviz installation.
    
            The current setting of library_dirs and include_dirs is:
    library_dirs=None
    include_dirs=None
    
    error: Error locating graphviz.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t2ega3lc/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-annpjoys/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-t2ega3lc/pygraphviz/

> 

getting the above errors.

**Comment by KevinHock** [comment] 2019-09-11 20:40
You're right that Graphviz can be difficult to install, especially on Linux, but I'm not sure what I can do to make it easier to install to be honest. I've had success on my OSX laptop. Do you have any ideas?

I could, after a lot of refactoring, make it so that `graphviz`/`pygraphviz` are optional dependencies. I have plans to do that, but it doesn't really solve the issue.

**Comment by jen140** [comment] 2019-11-27 11:34
Looks like the error explanation is a bit off. On debian based systems you also need to install "pkg-config", so to fix the issue on your Kali you just need to run the following:
sudo apt-get install pkg-config

For the full "one click" solution to all the dependency problems on debian based systems you just need to do(confirmed to work on deb9):
apt-get install graphviz graphviz-dev libgraphviz-dev pkg-config

**Comment by KevinHock** [comment] 2020-07-03 19:21
I'm gonna close this issue due to relating more to graphiz/pygraphviz than TrustTrees.

Thank you for documenting this so others can find it!

**Closed by KevinHock** 2020-07-03 19:21 UTC
Labels: dependencies
